#!/bin/sh
#
# Writes docs/POLICIES.md from policies/features.conf. The manifest is the only
# source of truth for what ships, so the documentation is generated from it
# rather than maintained beside it and allowed to drift.
#
# Run after changing the manifest. tests/run.sh fails if the output is stale.

set -eu

tools_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(dirname "$tools_dir")
MANIFEST="$repo_root/policies/features.conf"
OUT="${1:-$repo_root/docs/POLICIES.md}"

[ -f "$MANIFEST" ] || { printf 'manifest not found: %s\n' "$MANIFEST" >&2; exit 1; }

# Emits one pipe separated record per feature: id|name|summary|cost|presets|keys
# shellcheck disable=SC2016  # awk program: $0 and $1 are awk's, not the shell's
AWK_RECORDS='
  function flush() {
    if (cur == "") return
    order[++n] = cur
    rname[cur] = name; rsummary[cur] = summary; rcost[cur] = cost
    rpresets[cur] = presets; rkeys[cur] = keys
  }
  /^[ \t]*#/ { next }
  {
    ci = index($0, ":")
    if (ci == 0) next
    k = substr($0, 1, ci - 1)
    v = substr($0, ci + 1); sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v)
    if (k == "feature") {
      flush()
      cur = v; name = ""; summary = ""; cost = ""; presets = ""; keys = ""
      next
    }
    if (k == "name") name = v
    else if (k == "summary") summary = v
    else if (k == "cost") cost = v
    else if (k == "presets") presets = v
    else if (k == "policy" || k == "pref") {
      ei = index(v, " = ")
      key = (ei == 0) ? v : substr(v, 1, ei - 1)
      keys = keys (keys == "" ? "" : ", ") "`" key "`"
    }
  }
  END {
    flush()
    for (i = 1; i <= n; i++) {
      c = order[i]
      printf "%s|%s|%s|%s|%s|%s\n", c, rname[c], rsummary[c], rcost[c], rpresets[c], rkeys[c]
    }
  }
'

records() { awk "$AWK_RECORDS" "$MANIFEST"; }

# preset=standard lists everything in standard; preset=strict lists only what
# strict adds, since strict is a superset.
rows() {
  records | awk -F'|' -v preset="$1" -v mode="$2" '
    {
      inpreset = 0; instandard = 0
      n = split($5, p, " ")
      for (i = 1; i <= n; i++) {
        if (p[i] == preset) inpreset = 1
        if (p[i] == "standard") instandard = 1
      }
      if (!inpreset) next
      if (preset == "strict" && instandard) next
      cost = ($4 == "") ? "Nothing you would notice." : $4
      if (mode == "what") printf "| `%s` | %s | %s |\n", $1, $3, cost
      else printf "| `%s` | %s |\n", $1, $6
    }
  '
}

{
cat <<'HEADER'
# What FoxPrivacy changes

<!-- Generated by tools/gen-docs.sh from policies/features.conf. Do not edit. -->

Every setting, what it costs, and the exact policy or preference behind it.

## How these are applied

Most settings are [Firefox enterprise policies][policies]. Their names are
checked against Firefox's own `policies-schema.json` by the test suite, because
a policy key Firefox does not recognise is ignored without any error a user
would ever see.

The rest are preferences, applied through the `Preferences` policy. Firefox only
accepts preferences whose names match an allowlist in its source, so those are
checked too.

Preferences are applied with `Status: default`, which means FoxPrivacy changes
the default value and a value you set by hand still wins. If you once turned one
of these on deliberately, FoxPrivacy will not turn it back off. That is the
intent: this project sets defaults, it does not override your decisions.

## Profiles

`standard` is the default. Nothing in it should be noticeable except the absence
of ads and nags. `strict` is standard plus everything in the second table, and
each of those has a cost worth reading first.

HEADER

printf '## Standard profile\n\n'
printf '| Feature | What it does | Cost |\n|---|---|---|\n'
rows standard what
printf '\n### Standard profile, policies and preferences used\n\n'
printf '| Feature | Keys |\n|---|---|\n'
rows standard keys

printf '\n## Strict profile adds\n\n'
printf '| Feature | What it does | Cost |\n|---|---|---|\n'
rows strict what
printf '\n### Strict profile additions, policies and preferences used\n\n'
printf '| Feature | Keys |\n|---|---|\n'
rows strict keys

cat <<'FOOTER'

## What is deliberately not here

App updates, Firefox Sync, the password manager, DNS-over-HTTPS, and Encrypted
Client Hello are left alone on purpose, and the test suite asserts that they
stay that way. The reasoning is in [VISION.md](VISION.md#what-is-deliberately-left-alone).

## Checking what is actually in effect

```sh
install/foxprivacy.sh --list      # every feature and its cost
install/foxprivacy.sh --verify    # is the file still installed and unmodified
```

Then restart Firefox and open `about:policies`. The Errors tab must be empty.
The Active tab shows what Firefox actually accepted, which is the only thing
that counts.

[policies]: https://firefox-admin-docs.mozilla.org/reference/policies/
FOOTER
} > "$OUT"

printf 'wrote %s\n' "$OUT"
